language: c++

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; 
 
install:
 - sudo apt-get install -qq g++-4.8;
 - export CXX="g++-4.8";

script:
 - $CXX main.cpp
 - ./a.out npuzzle.h a
 - $CXX compare_two_files.cpp
 - ./a.out solutions.out solutions_done.out
